user

insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Pammie', 'Davoren', '1976-07-13 00:45:19', 'student', 'Female', '2bPq4USIQaC');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Chryste', 'Le febre', '1992-01-09 06:39:11', 'extern teacher', 'Male', 'Nw4BFfhh1QVb');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Eva', 'Mathely', '1995-07-27 20:55:41', 'teacher', 'Male', 'abZLGokBs');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Alair', 'Allender', '1972-08-17 20:42:46', 'student', 'Female', 'RrUoqleU');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Aguie', 'Coverdill', '2000-06-04 10:07:54', 'student', 'Male', 'rFJNdTdTdTC');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Brinn', 'Colthard', '1984-02-15 03:10:18', 'student', 'Female', 'qD2jQl');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Doreen', 'Tuson', '1973-12-04 09:26:05', 'extern teacher', 'Male', 'w0xncjEqs7');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Akim', 'Rowthorn', '1982-05-16 03:09:18', 'extern teacher', 'Female', 'sBUnplX');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Madlen', 'Ilyas', '1974-06-27 17:16:00', 'student', 'Female', 'VbHPxwq');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Nertie', 'Millsap', '1985-02-26 17:50:03', 'student', 'Female', 'ZcnQFe');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Geoff', 'Reams', '1977-03-11 20:39:59', 'teacher', 'Male', 'TUMhRg');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Shaine', 'Harkness', '1976-05-21 19:37:07', 'extern teacher', 'Female', 'E3y0MAoCLhd');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Aleksandr', 'Haslum', '1998-03-03 21:25:10', 'teacher', 'Male', '1zTUojG9SkM');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Alyosha', 'Prescot', '1998-01-14 19:21:28', 'teacher', 'Female', 'b8iRvLdK4L1');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Devina', 'Clatworthy', '1993-01-30 09:45:59', 'student', 'Male', 'c3YNAuB');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Belinda', 'Hinsche', '1980-07-05 00:51:15', 'student', 'Male', 'L9douQ');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Morlee', 'Turpey', '1997-12-26 23:29:58', 'student', 'Female', 'oS2WqBXm');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Sidoney', 'Overil', '1995-11-29 16:38:07', 'student', 'Male', 'NqpsfW');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Agnola', 'Leele', '1987-05-24 01:27:14', 'student', 'Female', 'kZClF6j');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Yardley', 'Stops', '1983-10-12 06:09:33', 'student', 'Female', 'Ac25yewQ3k');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Jedediah', 'Bugbee', '1991-04-24 02:31:52', 'extern teacher', 'Male', 'nMdkwI');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Wanda', 'Launder', '1975-09-16 04:28:03', 'student', 'Female', 'Kh6cb1lUbn');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Dill', 'Croll', '1977-09-15 19:20:49', 'student', 'Male', 'K2FbZ24');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Ruddie', 'Cookes', '1984-12-27 09:06:14', 'student', 'Female', 'InJleJ');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Tan', 'Fancett', '1986-05-21 17:13:53', 'teacher', 'Male', 'EwZEFvUslxGk');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Abagail', 'Kauble', '1980-06-28 17:34:48', 'student', 'Male', 'CDK42doD4E3I');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Trev', 'Pocknell', '1980-02-25 07:15:16', 'student', 'Male', 'RITeTqaer');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Gusta', 'Brailey', '1996-03-17 00:34:44', 'teacher', 'Female', '8ous96QXOup');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Zane', 'Scading', '1979-06-01 01:34:22', 'teacher', 'Male', 'iPnVh1');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Deonne', 'Reardon', '1974-09-02 13:10:37', 'extern teacher', 'Female', 'C8eAvYtuFg');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Isador', 'Spoors', '1975-08-19 04:39:26', 'extern teacher', 'Male', 'DyJwlN7');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Rosanne', 'Dat', '1996-03-15 07:14:10', 'student', 'Male', 'n0NBHBaXA8v');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Marji', 'Thorneywork', '2000-09-21 14:34:52', 'teacher', 'Female', 'YLrn8j');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Vanya', 'Sells', '1985-01-16 20:06:17', 'teacher', 'Male', 'NN8vk7F');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Janis', 'Stodit', '1975-01-27 07:41:19', 'student', 'Male', 'Rcc5p1f2');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Cary', 'Balcock', '1990-01-17 03:49:24', 'teacher', 'Male', '7CYjfvq9');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Silva', 'Caldron', '1993-04-13 05:54:24', 'student', 'Male', 'PGZAnNWX');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Loy', 'Magauran', '1981-03-07 05:54:07', 'teacher', 'Female', 'V5Gn9nm');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Laurene', 'Keirle', '1998-03-13 21:08:55', 'student', 'Female', 'G0EPAgomNp');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Willey', 'Peche', '1980-05-26 12:33:43', 'student', 'Male', '5BmlBNYON');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Manolo', 'Giuron', '1994-02-16 13:32:46', 'teacher', 'Female', 'XXU8k2hduJEV');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Ahmed', 'Powderham', '1982-01-18 01:32:12', 'student', 'Female', 'CylwOus');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Angelico', 'MacHoste', '1983-11-02 06:18:59', 'student', 'Male', 'DnziAQfPDx');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Papageno', 'Boland', '1980-09-13 05:44:58', 'teacher', 'Female', 'upESEw1Ti');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Emelia', 'Hurll', '1977-12-28 00:53:38', 'student', 'Male', '4EkRsAAeZ');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Poppy', 'Labuschagne', '1981-11-16 04:52:32', 'student', 'Female', 'sUSNaSlIWE');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Reynolds', 'Sickert', '1999-08-23 04:49:39', 'student', 'Female', 'CfjGN9R');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Hollie', 'Chasmor', '1981-06-24 04:15:37', 'student', 'Female', 'kH39azQw');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Obediah', 'Adlem', '1982-07-18 21:44:08', 'student', 'Female', 'SJlBMU');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Arabella', 'Vearncomb', '1992-09-06 11:54:23', 'student', 'Female', 'kmUimTch');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Georgiana', 'Bembrick', '1995-02-25 09:57:41', 'administrator', 'Female', 'IiouOFfQ5Mja');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Cammy', 'Cominotti', '1994-04-16 07:11:38', 'teacher', 'Female', 'ePXxt5RGB');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Brigg', 'Tilburn', '1992-07-14 22:13:22', 'student', 'Male', 'hfoWa0Icr');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Antonio', 'Coxwell', '1985-02-02 15:32:55', 'student', 'Female', 'rxfAD50BHgIH');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Allyn', 'Ayton', '1997-10-25 19:27:32', 'teacher', 'Female', 'ArSmuZLy3rp');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Modestine', 'Ebbett', '1995-12-20 20:34:03', 'student', 'Male', 't8heWdOT3ik');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Linn', 'Soldi', '1987-08-08 18:11:18', 'student', 'Female', '254DAudbP72');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Lizzy', 'Dwelly', '1992-12-16 02:46:43', 'student', 'Female', 'DYofi5I');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Rosalia', 'Blas', '1990-12-12 19:07:37', 'student', 'Female', 'd7MjAXV3f');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Wilie', 'Ovesen', '1977-09-22 23:10:57', 'student', 'Male', '2V92hquC');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Chrisy', 'Maris', '1993-08-12 22:07:18', 'extern teacher', 'Female', 'ERsGo8MXO1');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Penn', 'Bradneck', '1984-07-30 10:29:57', 'student', 'Male', 'ZOXhTfCSfDw');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Moe', 'Hartin', '1975-07-07 21:04:42', 'student', 'Male', '4A72Qu341Wb');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Oswald', 'Goodhall', '1995-10-07 02:00:38', 'student', 'Male', '18vBvppB');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Callean', 'Rosenau', '1996-02-23 22:57:43', 'student', 'Female', 'gKgTckDY');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Heloise', 'Pyett', '1972-10-03 11:45:18', 'student', 'Female', '3If56W8');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Harold', 'Fitzharris', '1979-03-05 04:14:16', 'student', 'Female', 'Po25KS267l');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Nomi', 'Batchellor', '1991-08-19 20:12:32', 'student', 'Male', 'WkkJ41np2X');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Chandra', 'Rodgman', '2000-08-20 16:39:19', 'student', 'Male', '0XnFVj0E6I8z');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Alistair', 'Scholard', '1972-09-13 10:58:21', 'teacher', 'Male', 'nc3MV9');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Alfredo', 'Zemler', '1997-09-12 07:30:24', 'extern teacher', 'Male', 'mhRMjf9aod');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Kary', 'Gerok', '1974-08-03 13:47:40', 'student', 'Female', 'tx43o5ouKJw');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Ofelia', 'Crevagh', '1996-08-23 17:02:53', 'teacher', 'Female', 'BcuBZpLCe');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Charlie', 'Cruz', '1986-12-06 11:05:58', 'student', 'Male', 'F0YudBO1');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Marquita', 'Adel', '1993-01-16 21:45:23', 'teacher', 'Female', 'wCmwVQnbFoY');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Rivkah', 'Bayman', '1977-01-05 02:38:38', 'teacher', 'Male', '0fFmzSZQnLn');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Kirsti', 'Wavish', '1975-05-22 16:26:29', 'student', 'Male', 'MizDwhO2xjUE');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Natalina', 'Osboldstone', '1972-10-19 22:57:35', 'teacher', 'Male', 'Yt1DKVKsmTX');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Wanids', 'Ramas', '1994-02-14 02:49:44', 'teacher', 'Male', '6OCbnBwEfFS');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Archambault', 'Freschini', '1996-12-13 22:50:31', 'student', 'Male', 'UhUAfc');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Tomlin', 'Shackell', '1979-08-09 12:12:29', 'student', 'Male', '7Zg2f9KuCqts');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Laurie', 'Graver', '1990-06-09 14:01:13', 'student', 'Male', 'fkGrz9Z6k6d8');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Kale', 'Cregg', '1975-11-02 12:59:29', 'student', 'Female', 'bOTwwZ');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('August', 'Perrot', '1991-11-23 18:58:31', 'student', 'Male', 'S8PTt4dXQ');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Boigie', 'Keam', '1989-04-05 11:13:42', 'student', 'Male', 'ElFORT');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Beatrisa', 'Bussons', '1984-02-18 00:51:38', 'student', 'Male', 'ukGk6E0Nt');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Udale', 'Franssen', '1995-12-24 07:57:24', 'teacher', 'Female', 'KfuaM4AcO');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Gabriel', 'Dongall', '1980-09-08 17:18:26', 'student', 'Male', 'MBAUoJu9Vg');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Hebert', 'Brane', '1976-09-24 04:01:49', 'student', 'Male', 'XKvCQ86');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Millisent', 'Gebbe', '1992-04-25 08:25:04', 'student', 'Male', 'xacsgFPin');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Evan', 'Keward', '1997-02-02 12:20:48', 'student', 'Female', 'hR2ySal');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Allina', 'Kytter', '1988-03-22 12:44:35', 'student', 'Male', 'bLwL4DXnNjMX');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Dyane', 'Camell', '1974-05-07 10:07:04', 'student', 'Male', 'jVZHzQtJe');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Niki', 'Marton', '1998-08-15 22:45:50', 'extern teacher', 'Female', 'eNFBZSvM');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Letty', 'Hawkings', '1994-10-08 14:52:36', 'student', 'Male', 'V4ATHdbhEK');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Giff', 'Bracci', '1980-03-04 17:53:46', 'student', 'Male', 'jEsTJHrMOZX');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Sallee', 'Cecil', '1992-07-17 05:44:58', 'teacher', 'Female', 'Aac6We');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Brandise', 'Jamme', '1988-06-17 14:43:34', 'student', 'Male', 'co4GKFLCij');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Sherill', 'Brundall', '1990-08-06 18:12:54', 'student', 'Female', 'WVrSHc');
insert into public."user" (name, surname, date_of_birth, status, sex, password) values ('Kienan', 'Gerge', '1982-04-27 09:36:11', 'student', 'Male', 'JGk184eh');

ADDRESS

insert into public."address" (city, street, number, zip) values ('Marataizes', 'Goodland', '6049', '32450-000');
insert into public."address" (city, street, number, zip) values ('Tobi Village', 'Melrose', '210', null);
insert into public."address" (city, street, number, zip) values ('Pran Buri', 'Forster', '26799', '77120');
insert into public."address" (city, street, number, zip) values ('Hengshitang', 'Hermina', '50', null);
insert into public."address" (city, street, number, zip) values ('Concepción de Ataco', 'Cottonwood', '7', null);
insert into public."address" (city, street, number, zip) values ('Novais', 'Northview', '44538', '3660-410');
insert into public."address" (city, street, number, zip) values ('Taiobeiras', 'Melody', '9', '39550-000');
insert into public."address" (city, street, number, zip) values ('Dukla', 'Coleman', '74619', '38-450');
insert into public."address" (city, street, number, zip) values ('Kerbuyan', 'Grover', '84', null);
insert into public."address" (city, street, number, zip) values ('Fálanna', 'Namekagon', '0533', null);
insert into public."address" (city, street, number, zip) values ('Bratsigovo', 'Ryan', '69', '4585');
insert into public."address" (city, street, number, zip) values ('Tanda', 'Coleman', '6', null);
insert into public."address" (city, street, number, zip) values ('Xinzhou', 'Sheridan', '6694', null);
insert into public."address" (city, street, number, zip) values ('Paris 07', 'Walton', '8215', '75345 CEDEX 07');
insert into public."address" (city, street, number, zip) values ('Maiorca', 'Garrison', '20582', '3090-469');
insert into public."address" (city, street, number, zip) values ('Trudobelikovskiy', 'Granby', '33984', '353810');
insert into public."address" (city, street, number, zip) values ('Cergy-Pontoise', 'Kropf', '27', '95011 CEDEX');
insert into public."address" (city, street, number, zip) values ('Mocímboa', 'Duke', '5', null);
insert into public."address" (city, street, number, zip) values ('Mentaraman Satu', 'Macpherson', '7293', null);
insert into public."address" (city, street, number, zip) values ('Manjo', 'Scoville', '24', null);
insert into public."address" (city, street, number, zip) values ('Ar Rifā‘', 'Scott', '7474', null);
insert into public."address" (city, street, number, zip) values ('Sudikampir', 'Eagan', '73933', null);
insert into public."address" (city, street, number, zip) values ('Hurghada', 'Grim', '0', null);
insert into public."address" (city, street, number, zip) values ('Karangkedawung', 'Pleasure', '89894', null);
insert into public."address" (city, street, number, zip) values ('Kundung', 'Garrison', '41704', null);
insert into public."address" (city, street, number, zip) values ('Sierpc', 'Independence', '1', '09-200');
insert into public."address" (city, street, number, zip) values ('Tapado', 'Bartillon', '99', '4640-580');
insert into public."address" (city, street, number, zip) values ('Xizhong', 'Cordelia', '41', null);
insert into public."address" (city, street, number, zip) values ('Hushaat', 'Blaine', '94', null);
insert into public."address" (city, street, number, zip) values ('Prosperidad', 'Maple Wood', '88767', '4107');
insert into public."address" (city, street, number, zip) values ('Macheke', 'Manitowish', '192', null);
insert into public."address" (city, street, number, zip) values ('Anrong', 'Bultman', '962', null);
insert into public."address" (city, street, number, zip) values ('Partikan', 'Sherman', '4', null);
insert into public."address" (city, street, number, zip) values ('Dziergowice', 'Commercial', '84829', '47-244');
insert into public."address" (city, street, number, zip) values ('Bočar', 'Valley Edge', '415', null);
insert into public."address" (city, street, number, zip) values ('Wetzlar', 'Eliot', '6', '35581');
insert into public."address" (city, street, number, zip) values ('Stockholm', 'Sundown', '172', '111 95');
insert into public."address" (city, street, number, zip) values ('Almolonga', 'Burrows', '41747', '09013');
insert into public."address" (city, street, number, zip) values ('Mae Charim', 'Knutson', '44293', '55170');
insert into public."address" (city, street, number, zip) values ('Tiro', 'Arrowood', '4326', null);
insert into public."address" (city, street, number, zip) values ('Gexi', 'Everett', '63', null);
insert into public."address" (city, street, number, zip) values ('Gobabis', 'Stone Corner', '212', null);
insert into public."address" (city, street, number, zip) values ('Chavdar', 'Almo', '77', '2087');
insert into public."address" (city, street, number, zip) values ('Goúrnes', 'Barby', '30302', null);
insert into public."address" (city, street, number, zip) values ('Leigao', 'Arrowood', '56', null);
insert into public."address" (city, street, number, zip) values ('Gjinkar', 'Forest Run', '877', null);
insert into public."address" (city, street, number, zip) values ('Castrovirreyna', 'Goodland', '551', null);
insert into public."address" (city, street, number, zip) values ('Trelleborg', 'Jenifer', '427', '231 43');
insert into public."address" (city, street, number, zip) values ('Myhove', 'Fair Oaks', '71059', null);
insert into public."address" (city, street, number, zip) values ('Dubiecko', 'Homewood', '07428', '37-750');
insert into public."address" (city, street, number, zip) values ('Kumagaya', 'Esch', '12821', '360-0016');
insert into public."address" (city, street, number, zip) values ('Pyt-Yakh', 'Roxbury', '8', '628389');
insert into public."address" (city, street, number, zip) values ('Kamuli', 'Basil', '37007', null);
insert into public."address" (city, street, number, zip) values ('Lajkovac', 'Norway Maple', '02', null);
insert into public."address" (city, street, number, zip) values ('Dongping', 'Glendale', '07613', null);
insert into public."address" (city, street, number, zip) values ('Liberta', 'Blaine', '1152', null);
insert into public."address" (city, street, number, zip) values ('Kafr al Labad', 'Moose', '1', null);
insert into public."address" (city, street, number, zip) values ('Bulawin', 'Corry', '46', '7416');
insert into public."address" (city, street, number, zip) values ('Okhansk', 'Claremont', '46546', '618100');
insert into public."address" (city, street, number, zip) values ('Arapongas', 'Merchant', '54', '86700-000');
insert into public."address" (city, street, number, zip) values ('Mlimba', 'Ilene', '02', null);
insert into public."address" (city, street, number, zip) values ('Obeliai', 'Oriole', '4139', '42006');
insert into public."address" (city, street, number, zip) values ('Fengping', 'Clove', '33', null);
insert into public."address" (city, street, number, zip) values ('Tambakromo', 'Petterle', '64', null);
insert into public."address" (city, street, number, zip) values ('Johanneshov', 'Cascade', '34457', '121 36');
insert into public."address" (city, street, number, zip) values ('Miaoxi', 'Forster', '0263', null);
insert into public."address" (city, street, number, zip) values ('Andilamena', 'Fieldstone', '20', null);
insert into public."address" (city, street, number, zip) values ('Sabana Grande de Palenque', 'Waubesa', '61008', '11704');
insert into public."address" (city, street, number, zip) values ('Kalāt-e Nāderī', 'Crest Line', '2', null);
insert into public."address" (city, street, number, zip) values ('Jāsk', 'Fallview', '716', null);
insert into public."address" (city, street, number, zip) values ('Rantaupanjangkiri', 'Pearson', '6990', null);
insert into public."address" (city, street, number, zip) values ('Kamimaruko', 'Thackeray', '2919', '386-0404');
insert into public."address" (city, street, number, zip) values ('Polešovice', 'Carberry', '03567', '687 37');
insert into public."address" (city, street, number, zip) values ('Bendilwungu Lor', 'Helena', '74571', null);
insert into public."address" (city, street, number, zip) values ('Gīvī', 'Stang', '55', null);
insert into public."address" (city, street, number, zip) values ('Daping', 'Weeping Birch', '92', null);
insert into public."address" (city, street, number, zip) values ('Gaozhuang', 'Service', '78', null);
insert into public."address" (city, street, number, zip) values ('Dedenëvo', 'East', '59', '141860');
insert into public."address" (city, street, number, zip) values ('Mata Grande', 'Arizona', '77', '57540-000');
insert into public."address" (city, street, number, zip) values ('Luhe', 'East', '46', null);
insert into public."address" (city, street, number, zip) values ('Ifo', 'La Follette', '9258', null);
insert into public."address" (city, street, number, zip) values ('Severoural’sk', 'Bultman', '0247', '624486');
insert into public."address" (city, street, number, zip) values ('Wushan', 'Sullivan', '0716', null);
insert into public."address" (city, street, number, zip) values ('Na Yung', 'Marquette', '727', '41380');
insert into public."address" (city, street, number, zip) values ('Hongor', 'Parkside', '44', null);
insert into public."address" (city, street, number, zip) values ('Feitoria', 'Judy', '45', '4650-291');
insert into public."address" (city, street, number, zip) values ('Písečná', 'Northwestern', '4', '790 82');
insert into public."address" (city, street, number, zip) values ('Santol', 'Mifflin', '65719', '2516');
insert into public."address" (city, street, number, zip) values ('Tianxingchang', 'Montana', '34', null);
insert into public."address" (city, street, number, zip) values ('Duishan', 'Maywood', '7545', null);
insert into public."address" (city, street, number, zip) values ('Krasnapollye', 'Trailsway', '80170', null);
insert into public."address" (city, street, number, zip) values ('Skurup', 'Laurel', '8', '274 34');
insert into public."address" (city, street, number, zip) values ('Sabana Grande de Boyá', 'Bobwhite', '30512', '10405');
insert into public."address" (city, street, number, zip) values ('Dallas', 'La Follette', '88767', '75236');
insert into public."address" (city, street, number, zip) values ('Dębno', 'Pierstorff', '0814', '74-400');
insert into public."address" (city, street, number, zip) values ('Zhanjiang', 'Judy', '31858', null);
insert into public."address" (city, street, number, zip) values ('Washington', 'Valley Edge', '138', '20036');
insert into public."address" (city, street, number, zip) values ('Linköping', 'Oxford', '609', '580 07');
insert into public."address" (city, street, number, zip) values ('Vokhaïkó', 'Lawn', '48', null);
insert into public."address" (city, street, number, zip) values ('Fuquan', 'Dorton', '1695', null);

CONTACT


insert into public."contact" (faculty_email, primary_phone) values ('jbarclay0@facebook.com', '221-772-6528');
insert into public."contact" (faculty_email, primary_phone) values ('btidder1@bbb.org', '877-111-9420');
insert into public."contact" (faculty_email, primary_phone) values ('acrimmins2@examiner.com', '533-830-2067');
insert into public."contact" (faculty_email, primary_phone) values ('gwoolam3@netscape.com', '749-569-3760');
insert into public."contact" (faculty_email, primary_phone) values ('smelmeth4@desdev.cn', '164-204-1386');
insert into public."contact" (faculty_email, primary_phone) values ('amccumesky5@woothemes.com', '330-173-4106');
insert into public."contact" (faculty_email, primary_phone) values ('gvickarman6@networkadvertising.org', '606-451-5444');
insert into public."contact" (faculty_email, primary_phone) values ('sbilbrooke7@bing.com', '279-715-2156');
insert into public."contact" (faculty_email, primary_phone) values ('gbowie8@merriam-webster.com', '409-798-2003');
insert into public."contact" (faculty_email, primary_phone) values ('eantonoczyk9@phoca.cz', '263-915-6659');
insert into public."contact" (faculty_email, primary_phone) values ('hgilroya@globo.com', '800-735-2711');
insert into public."contact" (faculty_email, primary_phone) values ('aoxbieb@reuters.com', '369-756-9419');
insert into public."contact" (faculty_email, primary_phone) values ('mdinnegesc@stanford.edu', '263-335-0567');
insert into public."contact" (faculty_email, primary_phone) values ('gcornfieldd@mysql.com', '935-832-4878');
insert into public."contact" (faculty_email, primary_phone) values ('atallante@dagondesign.com', '378-397-5349');
insert into public."contact" (faculty_email, primary_phone) values ('vdawidmanf@wp.com', '602-997-3600');
insert into public."contact" (faculty_email, primary_phone) values ('qpawnsfordg@ameblo.jp', '396-326-0581');
insert into public."contact" (faculty_email, primary_phone) values ('ahuffyh@pen.io', '146-115-9536');
insert into public."contact" (faculty_email, primary_phone) values ('smillbergi@dion.ne.jp', '378-227-7756');
insert into public."contact" (faculty_email, primary_phone) values ('gbracknellj@marketwatch.com', '351-407-1138');
insert into public."contact" (faculty_email, primary_phone) values ('tosherrink@goodreads.com', '485-661-6809');
insert into public."contact" (faculty_email, primary_phone) values ('tparlourl@yale.edu', '114-204-4348');
insert into public."contact" (faculty_email, primary_phone) values ('givachyovm@aboutads.info', '782-901-2242');
insert into public."contact" (faculty_email, primary_phone) values ('abelln@webmd.com', '851-807-2066');
insert into public."contact" (faculty_email, primary_phone) values ('bsteedmano@cisco.com', '510-146-8355');
insert into public."contact" (faculty_email, primary_phone) values ('jcawseyp@omniture.com', '370-487-8025');
insert into public."contact" (faculty_email, primary_phone) values ('spetyakovq@imdb.com', '499-762-1510');
insert into public."contact" (faculty_email, primary_phone) values ('mmcquinr@1688.com', '399-918-2106');
insert into public."contact" (faculty_email, primary_phone) values ('zaynscombes@canalblog.com', '230-237-4963');
insert into public."contact" (faculty_email, primary_phone) values ('gogleviet@networksolutions.com', '465-280-3884');
insert into public."contact" (faculty_email, primary_phone) values ('jkillshawu@drupal.org', '492-240-3607');
insert into public."contact" (faculty_email, primary_phone) values ('bskeelsv@digg.com', '198-751-4935');
insert into public."contact" (faculty_email, primary_phone) values ('lvernauw@php.net', '398-232-6104');
insert into public."contact" (faculty_email, primary_phone) values ('kionsx@oakley.com', '890-251-8704');
insert into public."contact" (faculty_email, primary_phone) values ('bparratty@behance.net', '865-261-4437');
insert into public."contact" (faculty_email, primary_phone) values ('crapelliz@moonfruit.com', '177-993-9868');
insert into public."contact" (faculty_email, primary_phone) values ('jsoden10@nymag.com', '136-690-8835');
insert into public."contact" (faculty_email, primary_phone) values ('bcraister11@over-blog.com', '979-327-1578');
insert into public."contact" (faculty_email, primary_phone) values ('kboodle12@cloudflare.com', '657-673-9030');
insert into public."contact" (faculty_email, primary_phone) values ('iaimer13@shop-pro.jp', '786-406-4985');
insert into public."contact" (faculty_email, primary_phone) values ('mmatts14@edublogs.org', '886-504-5974');
insert into public."contact" (faculty_email, primary_phone) values ('ahanks15@amazonaws.com', '432-901-5205');
insert into public."contact" (faculty_email, primary_phone) values ('pcorteney16@wunderground.com', '371-687-6859');
insert into public."contact" (faculty_email, primary_phone) values ('slogan17@apache.org', '846-652-3456');
insert into public."contact" (faculty_email, primary_phone) values ('gdanby18@yolasite.com', '737-889-5090');
insert into public."contact" (faculty_email, primary_phone) values ('jkingcote19@amazonaws.com', '118-628-8878');
insert into public."contact" (faculty_email, primary_phone) values ('sknoles1a@digg.com', '937-171-5605');
insert into public."contact" (faculty_email, primary_phone) values ('fbrazil1b@home.pl', '549-566-3538');
insert into public."contact" (faculty_email, primary_phone) values ('hsumnall1c@intel.com', '775-999-4244');
insert into public."contact" (faculty_email, primary_phone) values ('bgoolden1d@php.net', '842-969-7301');
insert into public."contact" (faculty_email, primary_phone) values ('wchillistone1e@privacy.gov.au', '591-764-8541');
insert into public."contact" (faculty_email, primary_phone) values ('tpennacci1f@vistaprint.com', '644-654-7008');
insert into public."contact" (faculty_email, primary_phone) values ('atownsley1g@github.io', '298-164-8431');
insert into public."contact" (faculty_email, primary_phone) values ('gmcmenemy1h@chicagotribune.com', '752-583-9343');
insert into public."contact" (faculty_email, primary_phone) values ('cbowes1i@go.com', '996-869-8858');
insert into public."contact" (faculty_email, primary_phone) values ('dwoonton1j@google.es', '718-790-7682');
insert into public."contact" (faculty_email, primary_phone) values ('acharle1k@jigsy.com', '200-564-4801');
insert into public."contact" (faculty_email, primary_phone) values ('waughton1l@youtube.com', '982-440-4495');
insert into public."contact" (faculty_email, primary_phone) values ('lflanne1m@usgs.gov', '771-435-3682');
insert into public."contact" (faculty_email, primary_phone) values ('cnend1n@tamu.edu', '715-719-8384');
insert into public."contact" (faculty_email, primary_phone) values ('dperet1o@goo.gl', '169-929-9988');
insert into public."contact" (faculty_email, primary_phone) values ('cmedway1p@woothemes.com', '433-209-7836');
insert into public."contact" (faculty_email, primary_phone) values ('dshurville1q@fema.gov', '537-927-6727');
insert into public."contact" (faculty_email, primary_phone) values ('esprigg1r@apple.com', '433-887-3875');
insert into public."contact" (faculty_email, primary_phone) values ('gjohns1s@purevolume.com', '838-268-4695');
insert into public."contact" (faculty_email, primary_phone) values ('gmchugh1t@clickbank.net', '205-674-4131');
insert into public."contact" (faculty_email, primary_phone) values ('bnattrass1u@blog.com', '497-732-5535');
insert into public."contact" (faculty_email, primary_phone) values ('clucus1v@ocn.ne.jp', '859-290-3617');
insert into public."contact" (faculty_email, primary_phone) values ('avarndell1w@loc.gov', '442-670-6707');
insert into public."contact" (faculty_email, primary_phone) values ('kdaton1x@nydailynews.com', '241-954-0295');
insert into public."contact" (faculty_email, primary_phone) values ('kschultheiss1y@a8.net', '444-459-1932');
insert into public."contact" (faculty_email, primary_phone) values ('bpoleye1z@ameblo.jp', '351-210-7394');
insert into public."contact" (faculty_email, primary_phone) values ('dbiddlecombe20@unesco.org', '210-502-0017');
insert into public."contact" (faculty_email, primary_phone) values ('psancraft21@taobao.com', '675-309-4255');
insert into public."contact" (faculty_email, primary_phone) values ('cwoodfield22@opensource.org', '553-759-7674');
insert into public."contact" (faculty_email, primary_phone) values ('mclutterbuck23@ed.gov', '876-891-7204');
insert into public."contact" (faculty_email, primary_phone) values ('mverny24@twitpic.com', '746-250-2337');
insert into public."contact" (faculty_email, primary_phone) values ('lmeek25@pinterest.com', '744-427-8288');
insert into public."contact" (faculty_email, primary_phone) values ('kcochet26@free.fr', '369-348-2481');
insert into public."contact" (faculty_email, primary_phone) values ('ringliss27@hugedomains.com', '979-944-7016');
insert into public."contact" (faculty_email, primary_phone) values ('chubball28@cam.ac.uk', '731-517-5783');
insert into public."contact" (faculty_email, primary_phone) values ('lrubanenko29@arizona.edu', '982-692-7919');
insert into public."contact" (faculty_email, primary_phone) values ('lschaffler2a@spiegel.de', '942-888-3488');
insert into public."contact" (faculty_email, primary_phone) values ('scommusso2b@cafepress.com', '213-479-4642');
insert into public."contact" (faculty_email, primary_phone) values ('gklais2c@vkontakte.ru', '863-323-5131');
insert into public."contact" (faculty_email, primary_phone) values ('wfarrer2d@ft.com', '994-843-1359');
insert into public."contact" (faculty_email, primary_phone) values ('lferrini2e@tamu.edu', '712-582-8376');
insert into public."contact" (faculty_email, primary_phone) values ('gbelderson2f@ca.gov', '507-564-7027');
insert into public."contact" (faculty_email, primary_phone) values ('mdevany2g@mtv.com', '262-775-0427');
insert into public."contact" (faculty_email, primary_phone) values ('kbiasetti2h@wired.com', '627-392-4758');
insert into public."contact" (faculty_email, primary_phone) values ('ldelicate2i@reddit.com', '565-823-2721');
insert into public."contact" (faculty_email, primary_phone) values ('shambleton2j@washingtonpost.com', '689-200-0969');
insert into public."contact" (faculty_email, primary_phone) values ('acaswill2k@a8.net', '510-565-8616');
insert into public."contact" (faculty_email, primary_phone) values ('govendale2l@devhub.com', '833-925-8552');
insert into public."contact" (faculty_email, primary_phone) values ('khebdon2m@posterous.com', '490-434-4065');
insert into public."contact" (faculty_email, primary_phone) values ('jswiffan2n@cdbaby.com', '637-864-3177');
insert into public."contact" (faculty_email, primary_phone) values ('fcaustic2o@elegantthemes.com', '265-640-3694');
insert into public."contact" (faculty_email, primary_phone) values ('jdacth2p@ezinearticles.com', '725-293-9427');
insert into public."contact" (faculty_email, primary_phone) values ('poager2q@wired.com', '691-530-3948');
insert into public."contact" (faculty_email, primary_phone) values ('ifidock2r@wordpress.org', '210-486-7865');


COURSE

insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T8', 4);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T8', 1);
insert into public."course" (course_name, course_location, course_duration) values ('MET', 'T12', 5);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T10', 3);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T11', 1);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T10', 5);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T11', 5);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T11', 1);
insert into public."course" (course_name, course_location, course_duration) values ('MET', 'T8', 2);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T10', 4);
insert into public."course" (course_name, course_location, course_duration) values ('MET', 'T12', 3);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T11', 4);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T12', 5);
insert into public."course" (course_name, course_location, course_duration) values ('MET', 'T11', 3);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T8', 1);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T12', 2);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T11', 5);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T8', 1);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T8', 4);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T8', 4);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T12', 5);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T12', 4);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T11', 4);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T10', 2);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T10', 2);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T10', 1);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T10', 4);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T8', 1);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T12', 3);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T12', 3);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T10', 1);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T12', 4);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T11', 3);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T12', 5);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T8', 5);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T12', 2);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T8', 5);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T12', 1);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T8', 3);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T12', 2);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T10', 4);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T10', 5);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T11', 1);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T10', 3);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T10', 4);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T12', 4);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T11', 2);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T10', 5);
insert into public."course" (course_name, course_location, course_duration) values ('MET', 'T8', 1);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T8', 3);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T11', 1);
insert into public."course" (course_name, course_location, course_duration) values ('MET', 'T12', 5);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T11', 5);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T10', 1);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T8', 4);
insert into public."course" (course_name, course_location, course_duration) values ('MET', 'T10', 3);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T11', 1);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T12', 2);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T11', 3);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T11', 5);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T12', 4);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T12', 4);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T8', 3);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T10', 5);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T12', 2);
insert into public."course" (course_name, course_location, course_duration) values ('MET', 'T10', 4);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T8', 1);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T11', 3);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T12', 4);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T10', 4);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T12', 2);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T12', 2);
insert into public."course" (course_name, course_location, course_duration) values ('MET', 'T11', 2);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T12', 5);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T12', 2);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T12', 5);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T11', 4);
insert into public."course" (course_name, course_location, course_duration) values ('MET', 'T12', 5);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T10', 3);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T12', 5);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T8', 5);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T11', 4);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T12', 2);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T10', 5);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T12', 3);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T8', 5);
insert into public."course" (course_name, course_location, course_duration) values ('MET', 'T10', 3);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T8', 3);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T11', 3);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T11', 4);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T10', 2);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T12', 2);
insert into public."course" (course_name, course_location, course_duration) values ('AMT', 'T8', 4);
insert into public."course" (course_name, course_location, course_duration) values ('MET', 'T10', 5);
insert into public."course" (course_name, course_location, course_duration) values ('MET', 'T11', 4);
insert into public."course" (course_name, course_location, course_duration) values ('TLI', 'T8', 2);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T11', 1);
insert into public."course" (course_name, course_location, course_duration) values ('MET', 'T10', 1);
insert into public."course" (course_name, course_location, course_duration) values ('IBE', 'T8', 3);
insert into public."course" (course_name, course_location, course_duration) values ('SEE', 'T8', 4);

COURSE_GRADE


insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'D', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'C', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('B', 'F', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'A', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'F', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'D', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'A', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'F', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'D', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'D', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('B', 'A', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'B', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'D', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'F', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'F', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'F', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'C', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'B', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'C', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'C', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'C', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('B', 'F', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'C', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('B', 'B', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'F', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('B', 'F', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'F', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'C', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'B', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('B', 'B', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'B', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'B', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'F', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'D', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'B', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('B', 'A', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'C', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'A', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'B', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'A', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'F', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'D', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'B', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'A', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('B', 'F', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'F', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'B', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'D', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('B', 'F', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'D', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'B', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'D', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'D', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'B', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'F', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'A', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'C', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'C', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'A', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'D', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'F', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'C', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'D', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'B', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('B', 'C', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'A', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'B', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'C', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'B', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'A', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('B', 'A', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'D', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'C', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'A', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'B', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'D', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'D', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'B', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'A', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'A', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'D', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'B', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('B', 'C', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'F', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'D', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('B', 'A', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'D', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'C', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'A', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'D', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'A', 'C');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'C', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('A', 'A', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'C', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('C', 'C', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'F', 'A');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'D', 'B');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('B', 'C', 'F');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('F', 'F', 'D');
insert into public."course_grade" (test_grade, lab_grade, final_grade) values ('D', 'C', 'F');